#logging:
#  level:
#    root: debug
#    org:
#      springframework: debug

server:
  port: 9090
spring:
  application:
    name: gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: feedModule
          uri: lb://feed
          predicates:
            - Path=/feed/**
          filters:
            - RewritePath=/feed/(?<segment>.*),/$\{segment}
        - id: users
          uri: lb://users
          predicates:
            - Path=/user/**
          filters:
            - RewritePath=/user/(?<segment>.*),/$\{segment}


management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
    instance:
      preferIpAddress: true